---
swagger: "2.0"
info:
          version: "1.0.0"
                    title: ""
                    host: "localhost:8080"
                    basePath: "/SwaggerTest/rest"
                    schemes:
                            - "http"
